changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-changes
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐞
      labels:
        - "bug"
    - title: Other Changes
      labels:
        - "*"
    - title: Translations
      labels:
        - "translations"
