sudo: false

addons:
    apt_packages:
        - lib32stdc++6  # needed for spcomp

env:
    - SMVERSION=1.8
    - SMVERSION=1.9

before_script:
    # install smbuilder
    - git clone https://github.com/splewis/sm-builder
    - cd sm-builder
    - pip install --user -r requirements.txt
    - python setup.py install --prefix=~/.local
    - cd ..

    # install the sourcemod compiler
    - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMVERSION}"
    - wget $SMPACKAGE
    - tar xfz $(basename $SMPACKAGE)
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"

    - cd include
    - wget https://raw.githubusercontent.com/popoklopsi/System2/master/system2.inc
    - wget https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
    - wget https://raw.githubusercontent.com/thraaawn/SMJansson/master/pawn/scripting/include/smjansson.inc
    - cd ../../../..

script:
    - smbuilder --flags="-E"

notifications:
    email: true
