site_name: Get5
site_url: https://splewis.github.io/get5
repo_url: https://github.com/splewis/get5
repo_name: splewis/get5
edit_uri: https://github.com/splewis/get5/blob/master/documentation/docs
theme:
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.sections
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - swagger-ui-tag
nav:
  - Home: index.md
  - Setup:
      - Installation: installation.md
      - Configuration: configuration.md
  - Basics:
      - Getting Started: getting_started.md
      - Commands: commands.md
      - Pausing: pausing.md
      - Backup System: backup.md
      - Match Schema: match_schema.md
  - Advanced:
      - Developer API: developer_api.md
      - Events & Forwards: events_and_forwards.md
      - Player Stats System: stats_system.md
      - Translations: translations.md
  - Social:
      - Community & Support: community.md
markdown_extensions:
  - abbr
  - tables
  - meta
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
