name: Test Builds On Merge Creation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  testbuild:
    name: Test Compile On Pull Request
    runs-on: ubuntu-22.04
    env:
      OUTPUT_PATH: output/get5
      OUTPUT_SM_PATH: output/get5/addons/sourcemod
      SM_JSON_INC_PATH: get5/dependencies/sm-json/addons/sourcemod/scripting/include
      STEAMWORKS_URL: https://raw.githubusercontent.com/KyleSanderson/SteamWorks/1.2.3c/Pawn/includes/SteamWorks.inc
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'get5'
        submodules: true

    - uses: rumblefrog/setup-sp@master
      with:
        version: '1.10.x'

    - name: Get shorthand commit.
      id: vars
      run: |
        echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c1-6)"
        echo "::set-output name=get5_version::$(cat get5/scripting/get5/version.sp | grep -Eo '#define PLUGIN_VERSION "[0-9]+\.[0-9]+\.[0-9]+' | sed 's/#define PLUGIN_VERSION "//')"

    - run: | 
        wget $STEAMWORKS_URL -P steamworks
        mkdir -p $OUTPUT_SM_PATH/plugins/disabled
        sed -i -r "s#\#define PLUGIN_VERSION \"[0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z]+#\#define PLUGIN_VERSION \"${{ steps.vars.outputs.get5_version }}-${{ steps.vars.outputs.sha_short }}#g" get5/scripting/get5/version.sp
        cp -R get5/cfg $OUTPUT_PATH
        cp -R get5/translations $OUTPUT_SM_PATH
        cp -R get5/configs $OUTPUT_SM_PATH
        cp -R get5/scripting $OUTPUT_SM_PATH
        cp get5/README.md $OUTPUT_PATH
        cp get5/LICENSE $OUTPUT_PATH
        spcomp get5/scripting/get5.sp -i steamworks -i $SM_JSON_INC_PATH -o $OUTPUT_SM_PATH/plugins/get5.smx -E
        spcomp get5/scripting/get5_apistats.sp -i steamworks -i $SM_JSON_INC_PATH -o $OUTPUT_SM_PATH/plugins/disabled/get5_apistats.smx -E
        spcomp get5/scripting/get5_mysqlstats.sp -i steamworks -i $SM_JSON_INC_PATH -o $OUTPUT_SM_PATH/plugins/disabled/get5_mysqlstats.smx -E
