name: Publish MKDocs to GH Pages
on:
  pull_request:
    branches:
      - "development"
  push:
    branches:
      - "master"
      - "development"
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          cd documentation
          pip install -r requirements.txt
          git config user.name docs && git config user.email githubactions@github.com
          git fetch origin gh-pages --depth=1
          if [ ${{ github.ref }} == 'refs/heads/master' ]
          then
            mike deploy latest --push
          elif [ ${{ github.ref }} == 'refs/heads/development' ]
          then
            mike deploy dev --push
          else
            mike deploy PR-${{ github.head_ref || github.ref_name }}  --push
          fi
